### PR TITLE
Fix ember-assign deprecation

### LINKED ISSUE #479: Fix ember-assign deprecation warning
After updating to Ember 4 I am seeing thousands of these deprecation warnings coming from ember-data-factory-guy initializing.

https://github.com/emberjs/rfcs/blob/master/text/0750-deprecate-ember-assign.md

Fortunately the recommended solution is backwards-compatible and simple.
Replace this:
```
import { assign } from '@ember/polyfills';
```
with this:
```
import { assign as emberAssign } from '@ember/polyfills';

const assign = Object.assign || emberAssign;
```

### PR DESCRIPTION
**Pull request by drouhard**
## Purpose
Address deprecation warnings. (See https://github.com/emberjs/rfcs/blob/master/text/0750-deprecate-ember-assign.md)

Fix https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/479

## Summary
Follow the suggestion in the deprecation RFC and use a backwards-compatible helper for `assign` that pulls in `@ember-polyfill/assign` only when the consumer doesn't have `Object.assign`. (That is, for IE11 users).

### CODE REVIEW

File: addon/utils/polyfills.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+// https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/479
+// Delete this polyfill when ready to drop support for IE11
```
Comment (MoonScript) [inline addon/utils/polyfills.js:2]: We've already dropped support for IE11.

File: addon/mocks/mock-get-request.js [hunk 2]
```diff
@@ -3,7 +3,7 @@
 import { assert } from '@ember/debug';
 import { typeOf } from '@ember/utils';
 import { isArray } from '@ember/array';
-import { assign } from '@ember/polyfills';
+import { assign } from '../utils/polyfills';
```
Comment (MoonScript) [inline addon/mocks/mock-get-request.js:6]: We can remove this import and instead do this down on line 139:
```
          modelParams = Object.assign({ id: currentId }, options.attrs);
```

File: addon/utils/polyfills.js (hunk 1 above)
Comment (drouhard) [reply addon/utils/polyfills.js:2]: The BU app has dropped support for IE, but ember-data-factory-guy hasn't. I opened [this same PR upstream](https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/480) in that repo, and it's more likely to get merged in if it is backwards-compatible.

**Review by MoonScript — APPROVED** [review]
Nice job tracking this down; thanks for fixing this.
